# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site language
lang: en-US

# Site title
title: "Eduardo Reis"

# A description of your site for meta tag, search engine results.
description: """
I’m a radiologist turned an AI researcher.
\n
\n
Currently I’m a visiting scholar at Stanford AIMI Center, working in the intersection of Artificial Intelligence and Medicine.
\n
\n
I love working in AI! My ultimate purpose is to significantly contribute to the “discovery” of intelligence (even if I can just be an example of a rational being). Our best chance to understand intelligence is by creating AGI. Lets work together as a society to do that in a way that we will not regret.
\n
\n
Published BRAX, the Brazilian Chest X-ray Dataset
Open-sourced the PyTorch implementation of ConVIRT - contrastive learning for radiology images and text (before CLIP)
Released Brain Hemorrhage Annotations - Brain Hemorrhage Extended - BHX
At Hospital Israelita Albert Einstein:
\n
\n
Started the Health Story project, a medical history timeline to support research and a more personalized clinical practice
Ran the development of AI algorithms for diseases of national importance: Tuberculosis, COVID, Melanoma and Head CT
"""

# The subpath of your site, e.g. /blog, for generating urls.
baseurl: ""

# The base hostname & protocol of your site for where absolute urls are needed.
url: "https://edreismd.github.io"

# Favicon
favicon: images/ER.jpeg

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: ""

# Site navigation - each item must have a title and a url.
navigation:
  - text: About
    url: /about
  - text: Blog
    url: /
  # - text: Style Guide
  #   url: /style-guide/
  # - text: Tags
  #   url: /tags/
  # - text: Download
  #   url: https://github.com/JustGoodThemes/Scriptor-Jekyll-Theme

# The shortname for your Disqus site to enable comments.
disqus: edreisMD

# Colors
accent_color: '#2d72d9'

# Site footer
footer:
  content: ""
  has_social: true

# Plugins
plugins:
  - jekyll-paginate

# http://jekyllrb.com/docs/pagination/
paginate: 3
paginate_path: '/page:num/'


# Permalinks
permalink: /:title

# Conversion
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
